### ISSUE TITLE
How to get the HeaderView or FooterView?

### ISSUE THREAD

**Issue by NoahZu** [lopspower/HFRecyclerView#1]
I want to process them in MainActivity. Is there any methods to help me get them in MainActivity?Thank you very much.

**Comment by lopspower** [comment]
You need to use an Adapter and used it in your MainActivity.
Please check example: [MainAcivity](https://github.com/lopspower/HFRecyclerView/blob/master/hfrecyclerview-example/src/main/java/com/mikhaellopez/hfrecyclerviewexample/MainActivity.java) And [ExampleAdapter](https://github.com/lopspower/HFRecyclerView/blob/master/hfrecyclerview-example/src/main/java/com/mikhaellopez/hfrecyclerviewexample/ExampleAdapter.java)
