### ISSUE TITLE
Manifest merger failed : Attribute application@allowBackup

### ISSUE THREAD

**Issue by evil159** [lopspower/HFRecyclerView#3]
I imported the library to my app by gradle.
I got this building error :
"Manifest merger failed : Attribute application@allowBackup value=(false)".
I think you should remove allowBackup attribute from your library. (Lib should not have that attribute).

**Comment by lopspower** [comment]
Fix in new release version:
```groovy
compile 'com.mikhaellopez:hfrecyclerview:1.1.1'
```
